# Generated by Django 3.2.7 on 2022-10-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
