name: GitHub Actions
on: [push]
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            nginx
            api
            client
            postgres
          run: docker-compose -f ../../docker-compose.yml build 